resume_directory: ../data/input/resumes
summary_output_directory: ../data/output
data_schema_dir: ../data/schema

case_agnostic_whole_resume:
 greeklife:
 - sorority
 - fraternity
 certifications:
 - [chartered financial analyst,cfa]
 - [certified public accountant,cpa]


case_agnostic_education:
 top_10_universities:
  - [TU Delft, TUDelft, Delft University of Technology]
  - [Univerity of Twente, UTwente]
  - [University of Amsterdam]
  - [Vrije Univesriteit, VU University, VU Amsterdam]
  - [UChicago, University of Chicago]
  - Drake University
  - University of Iowa
 top_100_universities:
  - [California State Polytechnic University Pomona,Cal Poly Pomona]
  - [Central Georgia Technical College,CGTC]
  - [California State University - Bakersfield,CSU Bakersfield]
  - [California State University - Chico,CSU Chico]
  - [California State University - East Bay,CSU East Bay]
  - [California State University - Fresno,CSU Fresno]
  - [California State University - Fullerton,CSU Fullerton]


case_sensitive_education:
 associate_education_level:
  - [Associate of Arts,A.A.,AA]
  - [Associate of Science,A.S.,AS]
 bachelor_education_level:
  - [Bachelor of Arts,B.A.]
  - [Bachelor of Science,B.S.,BS]
  - [Bachelor of Engineering,B.E.]
  - [Bachelor of Business Administration,B.B.A.,BBA]
  - [Bachelor of Commerce,B.Comm]
  - [Bachelor of Law,LLB]
 master_education_level:
  - [Master of Business Administration,Masters of Business Administration,MBA,M.B.A.]
  - [Master of Fine Arts,Masters of Fine Arts,M.F.A.,MFA]
  - [Master in Business Finance,Masters in Business Finance,MBF]
  - [Master of Arts,Masters of Arts,M.A.,MA]
  - [Master of Science,Masters of Science,MSc,M.S.]
 doctor_education_level:
  - [J.D.,Juris Doctor]
  - [Medical Doctor,M.D.,MD]
  - [Doctor of Dental Surgery,D.D.S.,DDS]
  - [Doctor of Pharmacy,Pharm.D.]
  - [Doctor of Philosophy,PhD,Ph.D]
  - [Doctor of Medicine,MD,M.D.]
  - [Doctor of Dental Surgery,DDS,D.D.S.]


case_agnostic_languages:
 languages:
  - Dutch
  - English
  - German
  - Spanish
  - [Chinese, Mandarin]
  - French
  - Greek
  - Hebrew
  - Japanese
  - Hindi
  - Russian
  - Arabic
  - Punjabi
  - Bengali
  - Portuguese
  - Welsh
  - Danish
  - Czech
  - Italian